# Generated by Django 6.0.1 on 2026-01-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_locataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mois_concerne', models.DateField()),
                ('en_avance', models.BooleanField(default=False)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locataire')),
            ],
        ),
    ]
