# Generated by Django 6.0.1 on 2026-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locataire',
            name='email',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='loyer_mensuel',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='ville',
        ),
        migrations.AddField(
            model_name='locataire',
            name='numero',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='numero',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
