# Generated by Django 6.0.1 on 2026-01-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_locataire_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='loyer_mensuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
