# Generated by Django 6.0.1 on 2026-02-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_locataire_loyer_mensuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='en_avance',
            new_name='paye_en_avance',
        ),
    ]
