# Generated by Django 6.0.1 on 2026-02-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_en_avance_paiement_paye_en_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.proprietaire', verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.locataire', verbose_name='Locataire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mois_concerne',
            field=models.DateField(verbose_name='Mois concerné'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='paye_en_avance',
            field=models.BooleanField(default=False, verbose_name='Payé en avance'),
        ),
    ]
