# Generated by Django 6.0.1 on 2026-02-12 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paiement_proprietaire_alter_paiement_date_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locataires', to='core.proprietaire', verbose_name='Propriétaire'),
        ),
    ]
