# Generated by Django 6.0.1 on 2026-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_mois_concerne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mois_concerne',
            field=models.DateField(blank=True, null=True),
        ),
    ]
