# Generated by Django 6.0.1 on 2026-02-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_mois_concerne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mois_concerne',
            field=models.IntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True, verbose_name='Mois concerné'),
        ),
    ]
