# Generated by Django 6.0.1 on 2026-02-13 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_paiement_mois_concerne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.proprietaire', verbose_name='Propriétaire'),
            preserve_default=False,
        ),
    ]
