# Generated by Django 6.0.1 on 2026-02-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_paiement_montant_alter_paiement_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='annee',
            field=models.IntegerField(default=2026, verbose_name='Année'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(fields=('locataire', 'mois_concerne', 'annee'), name='unique_paiement_locataire_mois_annee'),
        ),
    ]
