# Generated by Django 6.0.1 on 2026-02-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_paiement_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='annee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année'),
        ),
    ]
