# Generated by Django 6.0.1 on 2026-02-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_paiement_annee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(fields=('locataire', 'mois_concerne', 'annee'), name='unique_paiement_locataire_mois_annee'),
        ),
    ]
