# Generated by Django 6.0.1 on 2026-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_paiement_unique_paiement_locataire_mois_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Compte Admin',
            },
        ),
    ]
