# Generated by Django 6.0.1 on 2026-02-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_admincompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='frais_ordure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Frais d'ordure"),
        ),
    ]
