# Generated by Django 6.0.1 on 2026-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_paiement_frais_ordure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='frais_ordure',
        ),
        migrations.AddField(
            model_name='paiement',
            name='frais_wc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais WC'),
        ),
    ]
