# Generated by Django 6.0.1 on 2026-05-29 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_paiement_frais_ordure_paiement_frais_wc'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='proprietaire',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='locataires', to='core.proprietaire', verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='locataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='core.locataire', verbose_name='Locataire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='core.proprietaire', verbose_name='Propriétaire'),
        ),
    ]
