# Generated by Django 6.0.1 on 2026-06-01 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Lotissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['zone__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('plan', models.FileField(blank=True, null=True, upload_to='plans/')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reservee', 'Réservée'), ('vendue', 'Vendue')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lotissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='core.lotissement')),
            ],
            options={
                'ordering': ['lotissement', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('comptant', 'Comptant'), ('echelonne', 'Échelonné')], max_length=20)),
                ('remarque', models.TextField(blank=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='core.acheteur')),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vente', to='core.parcelle')),
            ],
            options={
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('remarque', models.TextField(blank=True)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='core.vente')),
            ],
            options={
                'ordering': ['date_paiement'],
            },
        ),
        migrations.AddField(
            model_name='lotissement',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotissements', to='core.zone'),
        ),
    ]
