# Generated by Django 6.0.1 on 2026-06-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='lotissement',
        ),
        migrations.AlterModelOptions(
            name='parcelle',
            options={'ordering': ['terrain__zone__nom', 'reference']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['quartier__nom', 'nom']},
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='superficie',
        ),
        migrations.AddField(
            model_name='parcelle',
            name='superficie_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Superficie (m²)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='plan',
            field=models.FileField(blank=True, null=True, upload_to='plans/parcelles/'),
        ),
        migrations.AlterField(
            model_name='tranche',
            name='date_paiement',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrondissements', to='core.commune')),
            ],
            options={
                'ordering': ['commune__nom', 'nom'],
                'unique_together': {('nom', 'commune')},
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='core.arrondissement')),
            ],
            options={
                'ordering': ['arrondissement__nom', 'nom'],
                'unique_together': {('nom', 'arrondissement')},
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='quartier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.quartier'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('nom', 'quartier')},
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('superficie_ha', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Superficie (ha)')),
                ('nb_parcelles_prevues', models.IntegerField(default=0, verbose_name='Nb parcelles prévues')),
                ('plan', models.FileField(blank=True, null=True, upload_to='plans/terrains/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrains', to='core.zone')),
            ],
            options={
                'ordering': ['zone__nom', 'reference'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='terrain',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='core.terrain'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lotissement',
        ),
    ]
